# SonarCloud — https://sonarcloud.io/project/overview?id=SCI-PATH_user-management
sonar.projectKey=SCI-PATH_user-management
sonar.projectName=user-management
sonar.organization=sci-path

sonar.sources=backend/app
sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**,**/.venv/**

sonar.sourceEncoding=UTF-8
